/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventario;

import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ing.Ivan
 */
public class BajaProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltaEmpresa
     */
    public BajaProducto() {
        initComponents();
        txt_buscar.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSqlEmpresa = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        btnok = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Ventana Eliminar Producto");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, new java.awt.Color(0, 0, 0)), "Eliminar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 24), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos40x40/40x40-BUSCAR.png"))); // NOI18N
        jLabel10.setText("  BUSCAR ");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));

        txt_buscar.setBackground(new java.awt.Color(0, 0, 0));
        txt_buscar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_buscar.setForeground(new java.awt.Color(0, 204, 204));
        txt_buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_buscar.setCaretColor(new java.awt.Color(0, 204, 204));
        txt_buscar.setDisabledTextColor(new java.awt.Color(0, 204, 204));
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });

        TablaSqlEmpresa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, new java.awt.Color(102, 102, 102)));
        TablaSqlEmpresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaSqlEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Empresa", "Nombre Producto", "Cajas", "Unidades"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaSqlEmpresa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TablaSqlEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TablaSqlEmpresa.setOpaque(false);
        TablaSqlEmpresa.getTableHeader().setReorderingAllowed(false);
        TablaSqlEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaSqlEmpresaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaSqlEmpresa);

        btnok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventario/aceptar.png"))); // NOI18N
        btnok.setToolTipText("Eliminar Fila Seleccionada");
        btnok.setBorderPainted(false);
        btnok.setContentAreaFilled(false);
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnok)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventario/bannerproductos.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //-------------METODOS-------------//
    DefaultTableModel m;
    public void TablaEmpresa(String val){//Realiza la consulta de los productos que tenemos en la base de datos
        String titles[]={"Id","Empresa","Nombre Producto","Cajas","Unidades"};
        String reg[]=new String[5];
        String sentence="";
        m=new DefaultTableModel(null,titles);
        
         Connection con;
        con=Conexion.GetConnection();
        sentence="CALL SP_ProductosSel('%"+val+"%')";
              
        try {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sentence);
               while (rs.next()) {
                   reg[0]=rs.getString("idProductos");
                   reg[1]=rs.getString("Empresas_idEmpresas");
                   reg[2]=rs.getString("Nombre");
                   reg[3]=rs.getString("Cajas");
                   reg[4]=rs.getString("Unidades");
                   m.addRow(reg);//agrega el registro a la tabla
               }
            TablaSqlEmpresa.setModel(m);//asigna a la tabla el modelo creado
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
        }
    }

     public void EliminarProducto(){
         int filasel;
        String id;
        try{
            filasel=TablaSqlEmpresa.getSelectedRow();
            if (filasel==-1) {
                JOptionPane.showMessageDialog(null,"No se ha seleccionado ninguna fila","Advertencia",JOptionPane.WARNING_MESSAGE);
                txt_buscar.requestFocus();
            }else{
                int confirmado=javax.swing.JOptionPane.showConfirmDialog(null,"¿Realmente desea eliminar el producto?","Confirmación",JOptionPane.YES_OPTION);
                if(confirmado==JOptionPane.YES_OPTION){
                m=(DefaultTableModel) TablaSqlEmpresa.getModel();
                id=(String) m.getValueAt(filasel, 0);
                
                Connection con;
               con=Conexion.GetConnection();
                String sentence="";
                sentence="CALL SP_ProductoDel("+id+")";
                
                try {
                       PreparedStatement pst=con.prepareStatement(sentence);
                       pst.executeUpdate();
                       JOptionPane.showMessageDialog(null,"Producto eliminado correctamente","Información",JOptionPane.INFORMATION_MESSAGE);
                        //Limpia de nuevo todos los campos
                       TablaSqlEmpresa.setVisible(false);
                       txt_buscar.setText("");
                        txt_buscar.requestFocus();
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null,ex);
                            }
                            }else{
                            TablaEmpresa("");
                            TablaSqlEmpresa.setVisible(false);
                            txt_buscar.setText("");
                             txt_buscar.requestFocus();
                           JOptionPane.showMessageDialog(null, "Cancelado correctamente","Información",JOptionPane.ERROR_MESSAGE);
                                 }
                  }
        }catch(Exception e){
            e.printStackTrace();
            
        }
    }
    
    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        EliminarProducto();
    }//GEN-LAST:event_btnokActionPerformed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        //actualiza la tabla conforme a la letra que teclea
        if(txt_buscar.getText().trim().length()>=1){
            String filtro=txt_buscar.getText();
            TablaEmpresa(filtro);

            TablaSqlEmpresa.setVisible(true);

        } else{
            TablaSqlEmpresa.setVisible(false);
              }
    }//GEN-LAST:event_txt_buscarKeyReleased

    private void TablaSqlEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaSqlEmpresaMouseClicked
        if (evt.getClickCount()==2) {
            EliminarProducto();
        }
    }//GEN-LAST:event_TablaSqlEmpresaMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaSqlEmpresa;
    private javax.swing.JButton btnok;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
