/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventario;

import Conexion.Conexion;
import static Inventario.AltaProducto.NameEmpresa;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ing.Ivan
 */
public class SalidasAlmacen extends javax.swing.JInternalFrame {

    /**
     * Creates new form SalidasAlmacen
     */
    //Obtiene los datos al loguearse
    public String user = Login.Login.Usuario;
    public String pass = Login.Login.Password;
    public String NombreQuienAccedioSistema = "";
    public String idreferencia="";
    public int idd;

    Connection con = Conexion.GetConnection();
    //variables para resultados
    public static String totales = "";
    DefaultTableModel m;

    public SalidasAlmacen() {
        initComponents();
        CargarEmpresas();
        txtCodigo.setEnabled(false);
        boxEmpresas.requestFocus();
        CargarMaxCodigo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ventana_productos = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        Seleccionar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        btn_cerrarprod = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_productos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jLabel16 = new javax.swing.JLabel();
        txtcajas = new javax.swing.JTextField();
        MenuTabla = new javax.swing.JPopupMenu();
        FilaDel = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSolicitante = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_guardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        boxEmpresas = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnBuscarNombre = new javax.swing.JButton();
        btnBuscarProductos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_productos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        btnBuscarSolicitante = new javax.swing.JButton();

        Ventana_productos.setTitle("Agregar nuevo producto");
        Ventana_productos.setMinimumSize(new java.awt.Dimension(706, 291));
        Ventana_productos.setModalityType(null);
        Ventana_productos.setUndecorated(true);
        Ventana_productos.setType(java.awt.Window.Type.UTILITY);
        Ventana_productos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda De Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium", 1, 14), new java.awt.Color(255, 51, 0))); // NOI18N
        jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel4ComponentShown(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos40x40/40x40-BUSCAR.png"))); // NOI18N
        jLabel10.setText("BUSCAR ");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 255), new java.awt.Color(0, 102, 255)));
        jPanel4.add(jLabel10);
        jLabel10.setBounds(30, 30, 120, 40);

        txt_buscar.setBackground(new java.awt.Color(0, 0, 0));
        txt_buscar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_buscar.setForeground(new java.awt.Color(51, 204, 255));
        txt_buscar.setCaretColor(new java.awt.Color(0, 153, 255));
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });
        jPanel4.add(txt_buscar);
        txt_buscar.setBounds(150, 30, 530, 40);

        Seleccionar.setBackground(new java.awt.Color(255, 255, 255));
        Seleccionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Seleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos20x20/20x20-OK.png"))); // NOI18N
        Seleccionar.setToolTipText("Aceptar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });
        Seleccionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SeleccionarKeyPressed(evt);
            }
        });
        jPanel4.add(Seleccionar);
        Seleccionar.setBounds(590, 240, 40, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("UNIDADES");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(40, 240, 110, 40);

        cantidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 0, 255));
        cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad.setText("1");
        cantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cantidadMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cantidadMouseExited(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadKeyTyped(evt);
            }
        });
        jPanel4.add(cantidad);
        cantidad.setBounds(150, 240, 100, 40);

        btn_cerrarprod.setBackground(new java.awt.Color(255, 255, 255));
        btn_cerrarprod.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_cerrarprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos20x20/20X20-CANCEL.png"))); // NOI18N
        btn_cerrarprod.setToolTipText("Salir");
        btn_cerrarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarprodActionPerformed(evt);
            }
        });
        jPanel4.add(btn_cerrarprod);
        btn_cerrarprod.setBounds(640, 240, 40, 40);

        table_productos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUCTO", "ID EMPRESA", "NOMBRE PRODUCTO", "CAJAS", "UNIDADES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_productos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table_productos.setOpaque(false);
        table_productos.getTableHeader().setReorderingAllowed(false);
        table_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_productosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_productos);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(30, 80, 650, 150);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("CAJAS");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(280, 240, 70, 40);

        txtcajas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtcajas.setForeground(new java.awt.Color(0, 0, 255));
        txtcajas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcajas.setText("0");
        txtcajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcajasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtcajasMouseExited(evt);
            }
        });
        txtcajas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcajasKeyTyped(evt);
            }
        });
        jPanel4.add(txtcajas);
        txtcajas.setBounds(350, 240, 100, 40);

        Ventana_productos.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 300));

        FilaDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos20x20/20X20-CANCEL.png"))); // NOI18N
        FilaDel.setText("Eliminar Fila");
        FilaDel.setToolTipText("Eliminar fila seleccionada");
        FilaDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilaDelActionPerformed(evt);
            }
        });
        MenuTabla.add(FilaDel);

        setClosable(true);
        setIconifiable(true);
        setTitle("Remisión");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos40x40/40x40-SALIDASALMACEN.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, new java.awt.Color(0, 0, 0)), "Generar Remisión", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 16)); // NOI18N
        jLabel1.setText(" Empresa:");

        txtSolicitante.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtSolicitante.setToolTipText("Nombre de quien solicito la Remisión");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventario/SalidaAlmacen.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 0, 12))); // NOI18N

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos20x20/20x20-Guardar.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setToolTipText("Guardar Remisión");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos20x20/20X20-CANCEL.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setToolTipText("Cancelar | Limpiar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncancelar)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_guardar)
                    .addComponent(btncancelar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Sitka Subheading", 1, 16)); // NOI18N
        jLabel13.setText("N° Remision:");

        txtCodigo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        boxEmpresas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        boxEmpresas.setToolTipText("Selecciona una empresa");

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 1, 16)); // NOI18N
        jLabel2.setText("Solicitante:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, new java.awt.Color(153, 153, 153)), "Datos de quien recibe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Subheading", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Sitka Subheading", 1, 16)); // NOI18N
        jLabel14.setText("¿Que recibio?");

        jLabel15.setFont(new java.awt.Font("Sitka Subheading", 1, 16)); // NOI18N
        jLabel15.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNombre.setToolTipText("Nombre de quien recibe.");

        btnBuscarNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscarNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos40x40/40x40-BUSCAR.png"))); // NOI18N
        btnBuscarNombre.setText("BUSCAR");
        btnBuscarNombre.setToolTipText("Click para abrir ventana");
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });

        btnBuscarProductos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos40x40/40x40-BUSCAR.png"))); // NOI18N
        btnBuscarProductos.setText("BUSCAR");
        btnBuscarProductos.setToolTipText("Click para abrir ventana");
        btnBuscarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductosActionPerformed(evt);
            }
        });

        Tabla_productos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, new java.awt.Color(102, 102, 102)));
        Tabla_productos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tabla_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUCTO", "EMPRESA", "NOMBRE PRODUCTO", "UNIDADES", "CAJAS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_productos.setToolTipText("Click derecho para abrir (MENU)");
        Tabla_productos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Tabla_productos.setComponentPopupMenu(MenuTabla);
        Tabla_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tabla_productos.setInheritsPopupMenu(true);
        Tabla_productos.setOpaque(false);
        Tabla_productos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tabla_productos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarProductos))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarNombre)))
                .addContainerGap(537, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(btnBuscarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(55, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(54, Short.MAX_VALUE)))
        );

        btnBuscarSolicitante.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscarSolicitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos40x40/40x40-BUSCAR.png"))); // NOI18N
        btnBuscarSolicitante.setText("BUSCAR");
        btnBuscarSolicitante.setToolTipText("Click para abrir ventana");
        btnBuscarSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSolicitanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarSolicitante))
                            .addComponent(boxEmpresas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(boxEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBuscarSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(233, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CargarMaxCodigo() {
        Connection con;
        con = Conexion.GetConnection();

        //Cargar el maximo codigo 
        String consulta = "SELECT coalesce(MAX(id), 0)+1 AS Identificador\n" +
"FROM Remisiones;";
        try {
            java.sql.Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(consulta);
            while (rs.next()) {
                String CodigoMax = rs.getString("Identificador");
                txtCodigo.setText(CodigoMax);

            }

            rs.close();

        } catch (Exception SQL) {
            System.out.println(SQL.getMessage());
        }
    }

    public void CargarEmpresas() {

        Connection con;
        con = Conexion.GetConnection();

        //Vista para cargar las empresas en el combobox
        String consulta = "SELECT * FROM vw_empresasel";
        try {
            java.sql.Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(consulta);
            while (rs.next()) {
                NameEmpresa = rs.getString("Nombre");
                boxEmpresas.addItem(NameEmpresa);

            }

            rs.close();

        } catch (Exception SQL) {
            System.out.println(SQL.getMessage());
        }
    }

    public void ObtenerNombreQuienAccedioSistema() {

        Connection con;
        con = Conexion.GetConnection();

        //Vista para cargar las empresas en el combobox
        String consulta = "CALL SP_ObtenerNombreQuienInicio('" + user + "','" + pass + "')";
        try {
            java.sql.Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(consulta);
            while (rs.next()) {
                NombreQuienAccedioSistema = rs.getString("U.Nombre");
            }

            rs.close();

        } catch (Exception SQL) {
            System.out.println(SQL.getMessage());
        }
    }

    public void InsertarRemision() {
        ObtenerNombreQuienAccedioSistema();

        String emp = boxEmpresas.getSelectedItem().toString();
        String sol = txtSolicitante.getText();
        String nom = txtNombre.getText();
        //String ent=¿Nombre quien entrego?

        //REGISTRAR LAS REMISIONES
        //Todos textfield estan llenados
        if (!emp.trim().isEmpty()
                && !sol.trim().isEmpty()
                && !nom.trim().isEmpty()) {

            int confirmado = JOptionPane.showConfirmDialog(null, "¿Esta seguro de generar la remision?", "Confirmación", JOptionPane.YES_OPTION);
            if (JOptionPane.YES_OPTION == confirmado) {
                Connection miConexion = (Connection) Conexion.GetConnection();
                try {
                    Statement statement = (Statement) miConexion.createStatement();
                    statement.executeUpdate("CALL Remision ('" + emp + "','" + sol + "','" + nom + "','" + NombreQuienAccedioSistema + "') ");

                    int numfilas = Tabla_productos.getRowCount();//retorna el numero de filas que hay en la tabla
                    System.out.println("num filas: "+numfilas);
                    
                    
                   
                    for (int i = 0; i < numfilas; i++) {
                        String id=Tabla_productos.getValueAt(i, 0).toString();
                        int id2=Integer.parseInt(id);
                        String nombre = Tabla_productos.getValueAt(i, 2).toString();
                        String uni = Tabla_productos.getValueAt(i, 3).toString();
                        String caj = Tabla_productos.getValueAt(i, 4).toString();
                        Connection miConexion1 = (Connection) Conexion.GetConnection();
                        try{
                           
                        Statement statement1 = (Statement) miConexion1.createStatement();
                        statement1.executeUpdate("CALL SP_ArtEntIns ('" + nombre + "'," + idd+ "," + uni+ "," + caj+ ") ");
                        
                        //Disminuir productos
                        Statement statement2 = (Statement) miConexion1.createStatement();
                        statement2.executeUpdate("CALL SP_DisminuirProductos (" + caj + "," + uni+ "," + id2+ ") ");
                        
                        }catch(Exception e){
                            e.printStackTrace();
                                            }
                    }

                    miConexion.close();

                    JOptionPane.showMessageDialog(this, "Remision guardada correctamente...","Información",JOptionPane.INFORMATION_MESSAGE);
                    Limpiar();
                    Tabla_productos.setVisible(true);
                    table_producto("");
                    CargarMaxCodigo();

                    paquete_reportes.Reportes re = new paquete_reportes.Reportes();//CREAMOS UN OBJETO DE LA CLASE REPORTES
                    String ruta = "C:\\Remision\\src\\SaveReports\\Remision.jasper";//RUTA DONDE TIENEN SU REPORTE --

                    //ABRIR CUADRO DE DIALOGO PARA GUARDAR EL ARCHIVO         
                    JFileChooser fileChooser = new JFileChooser();
                    fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("todos los archivos *.PDF", "pdf", "PDF"));//filtro para ver solo archivos .pdf
                    int seleccion = fileChooser.showSaveDialog(null);//para guardar save u open para abrir pdf
                    try {
                        if (seleccion == JFileChooser.APPROVE_OPTION) {//comprueba si ha presionado el boton de aceptar
                            File JFC = fileChooser.getSelectedFile();
                            String PATH = JFC.getAbsolutePath();//obtenemos la direccion del archivo + el nombre a guardar

                            try (PrintWriter printwriter = new PrintWriter(JFC)) {
                                printwriter.print(ruta);
                            }
                            re.resportesPDF(ruta, PATH);//mandamos como parametros la ruta del archivo a compilar y el nombre y ruta donde se guardaran    
                            //comprobamos si a la hora de guardar obtuvo la extension y si no se la asignamos
                            if (!(PATH.endsWith(".pdf"))) {
                                JOptionPane.showMessageDialog(null, "Espere.....", "Estamos Generando el Reporte", JOptionPane.WARNING_MESSAGE);
                                File temp = new File(PATH + ".pdf");
                                JFC.renameTo(temp);//JFCrenombramos el archivo
                                
                            }
                            
                            JOptionPane.showMessageDialog(null, "Documento Exportado Exitosamente!", "Guardado exitoso!", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } catch (FileNotFoundException | HeadlessException e) {//por alguna excepcion salta un mensaje de error
                        JOptionPane.showMessageDialog(null, "Error al Exportar el archivo!", "Contacta al programador", JOptionPane.ERROR_MESSAGE);

                    }

                } catch (Exception ex) {

                    JOptionPane.showMessageDialog(this, "Error en el try 1" + ex.getMessage());
                }

            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Cancelado correctamente","Información",JOptionPane.ERROR_MESSAGE);
        }

    }

    public void Limpiar() {
        m = (DefaultTableModel) Tabla_productos.getModel();
		m.setNumRows(0);
        boxEmpresas.setSelectedIndex(0);
        txtSolicitante.setText("");
        Tabla_productos.setVisible(false);
        table_producto("");
        txtNombre.setText("");
        boxEmpresas.requestFocus();

    }

    public void table_producto(String val) {//Realiza la consulta de los productos que tenemos en la base de datos
        String titles[] = {"ID PRODUCTO", "EMPRESA", "NOMBRE PRODUCTO", "UNIDADES", "CAJAS" };//titulos de la tabla
        String reg[] = new String[5];//tamaño del arreglo
        String consulta = "";//guardara la consulta
        m = new DefaultTableModel(null, titles);//asigna los titulos a la tabla
        //realiza una conexion
        Connection con;
        con = Conexion.GetConnection();
        //consulta en la base de datos
        consulta = "CALL SP_ProductosSel('%" + val + "%')";
        try {
            //ejecuta la consulta
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(consulta);
            //obtiene los datos de la consulta y los guarda en el arreglo
            while (rs.next()) {
                reg[0] = rs.getString("p.idProductos");
                reg[1] = rs.getString("e.Nombre");
                reg[2] = rs.getString("p.Nombre");
                reg[3] = rs.getString("p.Unidades");
                reg[4] = rs.getString("p.Cajas");
                m.addRow(reg);//agrega el registro a la tabla

            }
            rs.close();

            table_productos.setModel(m);//asigna a la tabla el modelo creado

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        //sacar el maximo id para referencia
        Connection miConexion2 = (Connection) Conexion.GetConnection();
		String consulta="CALL getUltimoIdReferencia()";
                try {
                   //ejecuta la consulta
			Statement st = miConexion2.createStatement();
			ResultSet rs = st.executeQuery(consulta);
                        while(rs.next()){
                        idreferencia=rs.getString("Referencia");
                         idd=Integer.parseInt(idreferencia);
                           
                        }
                    rs.close();
                }catch(SQLException e){ 
                    e.printStackTrace();
                }
        
        //Finalmente se inserta la remision
        InsertarRemision();
        Limpiar();
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        int resp = javax.swing.JOptionPane.showConfirmDialog(this, "¿Esta seguro de cancelar la remisión?", "Confirmación", JOptionPane.YES_OPTION);
	    if (resp == JOptionPane.YES_OPTION) {
		    Limpiar();
	    }
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnBuscarSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSolicitanteActionPerformed
        ListaNombres dialog = new ListaNombres(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnBuscarSolicitanteActionPerformed

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        ListaNombres1 dialog = new ListaNombres1(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void btnBuscarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductosActionPerformed
        //muestra la ventana para buscar y agregar productos a la venta
        Ventana_productos.setVisible(true);
    }//GEN-LAST:event_btnBuscarProductosActionPerformed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        //CODIGO CORRECTO
        if (txt_buscar.getText().trim().length() >= 1) {
            String filtro = txt_buscar.getText();
            table_producto(filtro);

            table_productos.setVisible(true);

        } else {
            table_productos.setVisible(false);

        }

    }//GEN-LAST:event_txt_buscarKeyReleased

    public void agregar_producto_tabla_venta() {
        int filasel = table_productos.getSelectedRow();
        String idp, ide, pro, cajas, cant;

        if (filasel == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún producto", "Advertencia", JOptionPane.WARNING_MESSAGE);
            txt_buscar.setText("");
            txt_buscar.requestFocus();
            table_productos.setVisible(false);
        } else {
            m = (DefaultTableModel) table_productos.getModel();
            //Obtenemos los datos de la tabla de productos
            idp = table_productos.getValueAt(filasel, 0).toString();
            ide = table_productos.getValueAt(filasel, 1).toString();
            pro = table_productos.getValueAt(filasel, 2).toString();
            cant = cantidad.getText();
            cajas= txtcajas.getText();

            if (Integer.parseInt(cant) <= 0) {
                cantidad.setText("1");
                cant = cantidad.getText();
            }

            m = (DefaultTableModel) Tabla_productos.getModel();
            //String filaelemento[] = {idp, ide, pro, caj, uni, cant};
            String filaelemento[] = {idp, ide, pro, cant, cajas};
            m.addRow(filaelemento);

            //limpia los campos
            txt_buscar.setText("");
            txt_buscar.requestFocus();
            table_productos.setVisible(false);
        }

    }

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        agregar_producto_tabla_venta();
        cantidad.setText("1");
        txtcajas.setText("0");
                

        if (cantidad.getText() == "") {
            javax.swing.JOptionPane.showMessageDialog(null, "No hay cantidad de productos para agregarlos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        Tabla_productos.setVisible(true);
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void SeleccionarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SeleccionarKeyPressed

    }//GEN-LAST:event_SeleccionarKeyPressed

    private void cantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cantidadMouseClicked
        cantidad.setText(null);
    }//GEN-LAST:event_cantidadMouseClicked

    private void cantidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cantidadMouseExited

    }//GEN-LAST:event_cantidadMouseExited

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyTyped
        /////////////////////
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();//sirve para desechar los carateres que no cumplan con la condición
        }
        /////////////////////
    }//GEN-LAST:event_cantidadKeyTyped

    private void btn_cerrarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarprodActionPerformed
        Ventana_productos.dispose();
    }//GEN-LAST:event_btn_cerrarprodActionPerformed

    private void table_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_productosMouseClicked
        if (evt.getClickCount() == 2) {
            agregar_producto_tabla_venta();
            cantidad.setText("1");
            txtcajas.setText("0");
            Tabla_productos.setVisible(true);
        }
    }//GEN-LAST:event_table_productosMouseClicked

    private void jPanel4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentShown

    }//GEN-LAST:event_jPanel4ComponentShown

    private void txtcajasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcajasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcajasMouseClicked

    private void txtcajasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcajasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcajasMouseExited

    private void txtcajasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcajasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcajasKeyTyped

    public void eliminar_fila_tabla(){
		int filasel = Tabla_productos.getSelectedRow();
		if (filasel == -1) {
			JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún producto", "Advertencia", JOptionPane.WARNING_MESSAGE);
		} else {
			m = (DefaultTableModel) Tabla_productos.getModel();
			m.removeRow(filasel);
			int numfilas = Tabla_productos.getRowCount();//retorna el numero de filas que hay en la tabla
			double suma_subtotales = 0.0;

			for (int i = 0; i < numfilas; i++) {
				String p1 = Tabla_productos.getValueAt(i, 4).toString();
				double valores = Double.parseDouble(p1);
				suma_subtotales = suma_subtotales + valores;

			}
			
		}
	}
    private void FilaDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilaDelActionPerformed
        eliminar_fila_tabla();
    }//GEN-LAST:event_FilaDelActionPerformed
    public static int aux = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem FilaDel;
    private javax.swing.JPopupMenu MenuTabla;
    private javax.swing.JButton Seleccionar;
    private javax.swing.JTable Tabla_productos;
    private javax.swing.JDialog Ventana_productos;
    private javax.swing.JComboBox boxEmpresas;
    public static javax.swing.JButton btnBuscarNombre;
    public static javax.swing.JButton btnBuscarProductos;
    private javax.swing.JButton btnBuscarSolicitante;
    private javax.swing.JButton btn_cerrarprod;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_productos;
    private javax.swing.JTextField txtCodigo;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtSolicitante;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txtcajas;
    // End of variables declaration//GEN-END:variables
}
