/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convertidor1;

/**
 *
 * @author ACER
 */
public class convertidor12 extends javax.swing.JFrame {

    /**
     * Creates new form convertidor
     */
    public convertidor12() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_limpiar = new javax.swing.JButton();
        bt_calcular = new javax.swing.JButton();
        bt_salir = new javax.swing.JButton();
        Centimetros = new javax.swing.JLabel();
        Centimetros1 = new javax.swing.JLabel();
        Centimetros2 = new javax.swing.JLabel();
        Centimetros3 = new javax.swing.JLabel();
        Centimetros4 = new javax.swing.JLabel();
        CONVERTIDOR = new javax.swing.JLabel();
        yardas = new javax.swing.JTextField();
        pulgadas = new javax.swing.JTextField();
        centimetros = new javax.swing.JTextField();
        millas = new javax.swing.JTextField();
        kilometros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_limpiar.setBackground(new java.awt.Color(255, 153, 0));
        bt_limpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_limpiar.setText("Limpiar");
        bt_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limpiarActionPerformed(evt);
            }
        });

        bt_calcular.setBackground(new java.awt.Color(255, 153, 0));
        bt_calcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_calcular.setText("Calcular");
        bt_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_calcularActionPerformed(evt);
            }
        });

        bt_salir.setBackground(new java.awt.Color(255, 153, 0));
        bt_salir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_salir.setText("Salir");
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });

        Centimetros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Centimetros.setText("Centimetros");

        Centimetros1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Centimetros1.setText("Yardas");

        Centimetros2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Centimetros2.setText("Pulgadas ");

        Centimetros3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Centimetros3.setText("Kilometros");

        Centimetros4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Centimetros4.setText("Millas");

        CONVERTIDOR.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CONVERTIDOR.setText("CONVERTIDOR");

        yardas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yardasActionPerformed(evt);
            }
        });

        pulgadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulgadasActionPerformed(evt);
            }
        });

        centimetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centimetrosActionPerformed(evt);
            }
        });

        millas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                millasActionPerformed(evt);
            }
        });

        kilometros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilometrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(bt_limpiar)
                        .addGap(46, 46, 46)
                        .addComponent(bt_calcular)
                        .addGap(44, 44, 44)
                        .addComponent(bt_salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Centimetros3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Centimetros2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Centimetros4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Centimetros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yardas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(centimetros, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Centimetros1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(millas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kilometros, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(CONVERTIDOR, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CONVERTIDOR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Centimetros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(centimetros, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Centimetros1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yardas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Centimetros2)
                .addGap(13, 13, 13)
                .addComponent(pulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Centimetros3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kilometros, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Centimetros4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(millas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(bt_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_calcularActionPerformed
        
        double cent,yar,pul,kil,mil,r1,r2,r3,r4;
         
        cent =  Double.parseDouble(centimetros.getText());
        pul = Double.parseDouble(pulgadas.getText());
        yar = Double.parseDouble(yardas.getText());
        kil = Double.parseDouble(kilometros.getText());
        mil = Double.parseDouble(millas.getText());
        
        //centimetros
        if (cent != 0 && yar==0 && pul==0 && kil==0 && mil==0){
            System.out.println("lel");
            
          r1 = cent/91.44;
          r2 = cent/2.54;
          r3 = cent/100000;
          r4 = cent/160934.4;
          
          //punto donde se muestra el valor
          yardas.setText(""+r1);
          pulgadas.setText(""+r2);
           kilometros.setText(""+r3);
          millas.setText(""+r4);
          
        }
        //yardas
        if (yar != 0 && cent==0 && pul==0 && kil==0 && mil==0){
            System.out.println("lul");
            
          r1 = yar*91.44;
          r2 = yar*36;
          r3 = yar/1093.613;
          r4 = yar/1760;
          
          //punto donde se muestra el valor
          centimetros.setText(""+r1);
          pulgadas.setText(""+r2);
           kilometros.setText(""+r3);
          millas.setText(""+r4);
          
        }
        //pulgadas
        if (pul != 0 && cent==0 && yar==0 && kil==0 && mil==0){
            System.out.println("lol");
            
          r1 = pul/36;
          r2 = pul*2.54;
          r3 = pul/63360;
          r4 = pul/39370.079;
          
          //punto donde se muestra el valor
          yardas.setText(""+r1);
          centimetros.setText(""+r2);
           kilometros.setText(""+r3);
          millas.setText(""+r4);
          
        }
         //kilometros
        if (kil != 0 && yar==0 && cent==0 && pul==0 && mil==0){
            System.out.println("lal");
            
          r1 = kil/1093613;
          r2 = kil*100000;
          r3 = kil*39370.079;
          r4 = kil/1.609;
          
          //punto donde se muestra el valor
          yardas.setText(""+r1);
          centimetros.setText(""+r2);
           pulgadas.setText(""+r3);
          millas.setText(""+r4);
          
        } //kilometros
        if (mil != 0 && yar==0 && cent==0 && pul==0 && kil==0){
            System.out.println("lil");
            
          r1 = mil*1760;
          r2 = mil*160934.4;
          r3 = mil*63360;
          r4 = mil*1.609;
          
          //punto donde se muestra el valor
          yardas.setText(""+r1);
          centimetros.setText(""+r2);
           pulgadas.setText(""+r3);
         kilometros.setText(""+r4);
          
        }
        
    }//GEN-LAST:event_bt_calcularActionPerformed

    private void bt_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpiarActionPerformed
          yardas.setText("0");
          centimetros.setText("0");
           pulgadas.setText("0");
          kilometros.setText("0");
          millas.setText("0");
          System.out.println("equis de");
          
    }//GEN-LAST:event_bt_limpiarActionPerformed

    private void yardasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yardasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yardasActionPerformed

    private void pulgadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulgadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pulgadasActionPerformed

    private void centimetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centimetrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centimetrosActionPerformed

    private void millasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_millasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_millasActionPerformed

    private void kilometrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilometrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kilometrosActionPerformed

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_bt_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(convertidor12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(convertidor12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(convertidor12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(convertidor12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new convertidor12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CONVERTIDOR;
    private javax.swing.JLabel Centimetros;
    private javax.swing.JLabel Centimetros1;
    private javax.swing.JLabel Centimetros2;
    private javax.swing.JLabel Centimetros3;
    private javax.swing.JLabel Centimetros4;
    private javax.swing.JButton bt_calcular;
    private javax.swing.JButton bt_limpiar;
    private javax.swing.JButton bt_salir;
    private javax.swing.JTextField centimetros;
    private javax.swing.JTextField kilometros;
    private javax.swing.JTextField millas;
    private javax.swing.JTextField pulgadas;
    private javax.swing.JTextField yardas;
    // End of variables declaration//GEN-END:variables
}
